### ISSUE TITLE
panic: not a trace file

### ISSUE THREAD

**Issue by struCoder** [divan/gotrace#14]
<img width="652" alt="wx20170621-160850 2x" src="https://user-images.githubusercontent.com/6498477/27373716-f5c6f11c-569b-11e7-9b28-1a634c78e84c.png">

Hope your help.
Thanks.

**Comment by divan** [comment]
Hey thanks for reporting.

I think I've updated docker image to use Go1.8 branch of gotrace (and the trace format is updated there). You may try to switch to this branch and reinstall `gotrace`:

```
git checkout go18
go install
```

But there are a few issues need to be solved until it's merged with master.

**Comment by struCoder** [comment]
@divan 
it works.

Thanks for your help.

**Comment by xueyouchao** [comment]
Quick question, I tried go18 version and it seems I don't need to use docker or the other way to patch the go runtime anymore. It just works straight, right?
